### ISSUE TITLE
ValueError: not enough values to unpack (expected 6, got 5)

### ISSUE THREAD

**Issue by izaskr** [aeye-lab/etra-reading-comprehension#7]
While running generate_text_sequence_splits.py, I get the following ValueError.

```
2022-06-15 17:02:57.126364: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-15 17:02:57.126392: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Calculating for text_id='reading-dickens-1'....
  0%|                                                                                                                        | 0/95 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/local/home/work/izaskr/etra-reading-comprehension/utils/generate_text_sequence_splits.py", line 278, in <module>
    raise SystemExit(main())
  File "/local/home/work/izaskr/etra-reading-comprehension/utils/generate_text_sequence_splits.py", line 260, in main
    label_arr, data_arr_CNN, label_dict, fix_data = load_text_sequence_data()
  File "/local/home/work/izaskr/etra-reading-comprehension/utils/generate_text_sequence_splits.py", line 105, in load_text_sequence_data
    features, features_names = feature_extraction.get_linguistic_features_for_lists(
  File "/local/home/work/izaskr/etra-reading-comprehension/utils/feature_extraction.py", line 342, in get_linguistic_features_for_lists
    deps, n_rights, rights, n_lefts, lefts, dep_distance = parse_dependency(
ValueError: not enough values to unpack (expected 6, got 5)
```

**Comment by SiQube** [comment]
I'm recreating the error locally and am currently fixing it -- patch should come later today

**Comment by SiQube** [comment]
I've also patched the ahn_baseline for the working directories -- another patch for our model (BEyeLSTM) will come soon. Then I hope everything works =) sorry for the inconveniece...

**Comment by SiQube** [comment]
last patch #10 is merged -- now everything should be working.
